### ISSUE TITLE
Discord server invite has a trailing /, breaking the url.

### ISSUE THREAD

**Issue by 6gk** [whyadamsalt/whyadamsalt.github.io#2]
currently: https://discord.gg/8bxNqn6epv/

what it should be: https://discord.gg/8bxNqn6epv

**Comment by whyadamsalt** [comment]
I'll fix this once I am home, thank you for notifying me!

**Comment by whyadamsalt** [comment]
Took a while but finally fixed after I updated all information on my web-page!

**Comment by 6gk** [comment]
Nice, looks like you forgot to fix it in the link part of index.md @ line 37 though.
